improve code

diff --git a/run b/run
--- a/run
+++ b/run
@@ -17,7 +17,7 @@ do
            continue;;
         "--min-coverage="* )
            MIN_COVERAGE="${opt#*=}";;
-        *) echo >&2 "Invalid option: $*"; exit 1;;
+        #*) echo >&2 "Invalid option: $@"; exit 1;;
    esac
 done
 
@@ -39,16 +39,13 @@ fi
 
 # Verifying if coverage has succeed
 if [ "$MIN_COVERAGE" -gt "0" ]; then
-    result=$(head .coverage -n 9 | tail -n 1 )
-
-    arr=(${result})
-    result=${arr[1]}
+    result=$(head -n9 .coverage | tail -n 1 )
     result=$(echo "$result" | cut -d '.' -f 1)
-
+    result="${result:8:${#result}}"
     rm .coverage
 
-    if [ "$result" -gt "$MIN_COVERAGE" ]; then
-        printf "\033[41m\033[37m Coverage is below %s \033[0m\n\n" "${MIN_COVERAGE}"
+    if [ "$result" -lt "$MIN_COVERAGE" ]; then
+        printf "\\033[41m\\033[37m Coverage is below %s \\033[0m" "$MIN_COVERAGE"
         exit 1
     fi
 fi
